### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by bis35** [kodi-iptv-addons/kodi-iptv-addons#2]
I have tried Ottplayer and I don't see the reason to use it on KODI. I am using simple client. Would be really nice if you could've create interface like Samsung TV. Good luck and thank you.

**Comment by dmitry-vinogradov** [comment]
Well...   If I will create an interface "like Samsung TV" you'll probably not see the reason to use it on KODI as well because you have Samsung TV ;) 
The purpose of this addons is to be able to see your IPTV provider content on devices which already have KODI installed, nothing more and nothing less.

So I'll close this issue because it's neither a feature request nor a bug.
